#!/usr/bin/env python3

"""
schoolcafe-parse — A parser for SchoolCafe PDF menus

This application takes a PDF file generated via SchoolCafe's print function,
saved to PDF via Chrome's `Save as PDF` option, and reads it via stdin and
writes a JSON format via stdout. This is intended to then be piped to the
schoolcafe-ics application.
"""

import io
import json
import sys
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime

from pypdf import PdfReader

# The last two lines of the first page are:
#   1. The school name
#   2. The calendar details, e.g., Lunch (Main), September - 2026 - Grade: PK

UNSET = datetime(1970, 1, 1)


@dataclass
class ParseResults:
    # Only the first page has the menu name, but we parse them in order
    school: str
    grade: str
    menu_name: str
    menu: dict


def parse(page: list[str]) -> ParseResults:
    """Parse the lines in a menu page and return their menu details

    This reads page text line by line and assembles a dictionary of daily menus and their options
    """

    # The last line in the file includes a details line, which we parse for year and month
    details = page.pop().strip()
    menu_name, remains = details.split(",")
    month_name, year, grade = remains.strip().split("-")
    grade = grade.strip()

    month = datetime.strptime(f"{month_name.strip()} {year.strip()}", "%B %Y")

    # The second to last line is the name of the school
    school = page.pop().strip()

    # As we pass the menu lines, which are ALL CAPS, set that we're inside one
    # so we append the following lines as items on that menu.
    # In the one-page print it appears to only allow one category, which on
    # our school's menu is 'ENTREES'. Not sure if that's standard for the platform.
    current_menu = ""
    menu: dict[str] = {}

    index = 0
    while index < len(page):
        # We don't pre-strip lines here because we append menu items as-is
        # so they render with newlines as they do inside the calendar version.
        line = page[index]

        try:
            current_day = int(line.strip())
            day = month.replace(day=current_day)
            # This key is useful in this format because it's how the date part
            # of an ICS formatted timestamp needs to be.
            day_key = day.strftime("%Y%m%d")

            current_menu = ""
            menu[day_key] = {}

            index += 1
            continue
        except ValueError:
            pass

        try:
            # If this line parses as just a day of the week, skip it
            # because we already have a real datetime
            datetime.strptime(f"{line.strip()}", "%A")

            index += 1
            continue
        except ValueError:
            pass

        # Menu names are uppercase, like ENTREES, which we'll use for grouping
        if line == line.upper() and line.strip() != current_menu:
            # Get rid of the all-caps name so it looks neater
            current_menu = line.strip().capitalize()
            menu[day_key][current_menu] = []
        else:
            menu[day_key][current_menu].append(line)

        index += 1

    return ParseResults(school=school, grade=grade, menu_name=menu_name, menu=menu)


def main() -> int:
    # We're reading bytes start-to-finish via stdin, but PdfReader needs a seekable buffer.
    with io.BytesIO(sys.stdin.buffer.read()) as input_stream:
        with PdfReader(input_stream) as reader:
            assert (
                len(reader.pages) == 1
            ), "This is designed to work with the 'Fit to One Page' printing option"

            text = reader.pages[0].extract_text().split("\n")
            result = parse(text)

            full_menu = result.menu
            full_menu["_metadata"] = {
                "School": result.school,
                "Grade": result.grade,
                "Menu": result.menu_name,
            }

            sys.stdout.write(json.dumps(full_menu))

    return 0


if __name__ == "__main__":
    sys.exit(main())
